version: 2
updates:
  - package-ecosystem: "pip" # Use "pip" for Python
    directory: "/" # Location of your requirements.txt or pyproject.toml
    schedule:
      interval: "weekly" # Check for updates once a week
